services:
  petclinic-server:
    build:
      context: .
      target: development
    ports:
      - "9966:9966"
      - "8000:8000"
    environment:
      - POSTGRES_URL=jdbc:postgresql://petclinic-db:5432/petclinic
    depends_on:
      petclinic-db:
        condition: service_healthy

  petclinic-db:
    image: postgres:16.0
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "petclinic" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
